formatVersion: 1
formatType: am-configuration
---
# basic AM functionality - the builtin apps are in 'apps'.

applications:
  builtinAppsManifestDir: "apps"

# QML apps will be able to import from modules...

runtimes:
  qml:
    importPaths: [ "imports/shared" ]
    environmentVariables: {LD_PRELOAD: "/usr/lib/libEGL.so.1"}

# ... as well as the SystemUI

ui:
  fullscreen: yes
  mainQml: "Main.qml"
  importPaths: [ "imports/shared", "imports/system" ]
  additionalConfiguration:
    appStoreServerUrl: 'http://chaos.pelagicore.net:8080'
    styleConfig: "auto"
    showCluster: yes
  windowIcon: "imports/shared/assets/icons/active/apps@96.png"

# development setup: no security

flags:
  noSecurity: yes
  noUiWatchdog: yes


